### ISSUE TITLE
Die Seite lässt sich nicht scrollen

### ISSUE THREAD

**Issue by YtvwlD** [td00/cybermorning.show#11]
Auf kleineren Bildschirmen passt die gesamte Seite nicht auf eine Bildschirmseite.
Und (zumindest mit Firefox 50 auf Android 4.4) kann ich nicht scrollen.

**Comment by TiiFuchs** [comment]
@YtvwlD Kannst du das jetzt nochmal überprüfen? :)

**Comment by TiiFuchs** [comment]
Fehler gefunden, und gebannt.

**Comment by YtvwlD** [comment]
Ja, geht jetzt.
