### ISSUE TITLE
Zeigen das P=NP

### ISSUE THREAD

**Issue by LongHairedHacker** [td00/cybermorning.show#20]
Für mehr Cyber sollte sich endlich mal wer darum kümmern zu beweisen, dass P eine echte Teilmenge von NP ist und umgekehrt.

**Comment by thies23** [comment]
Auf der Bühne erklärt!

**Comment by MichiK** [comment]
P = NP
=> N = P/P = 1
=> P = 1×P
=> P = NP

q.e.d.

**Comment by LongHairedHacker** [comment]
Aber P\P ist doch {} ... So kommt mir das nicht durchs  Code-Review.
